language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3.5"
  - "pypy3"
 
services:
  - docker

env:
  matrix:
    - KV_DB=redis ovs_version=2.5.9
    - KV_DB=zookeeper ovs_version=2.5.9
    - KV_DB=zookeeper ovs_version=2.9.5

# command to install dependencies
install: 
  - "pip install nstruct hiredis pychecktype"
  - pip install coverage

cache:
  directories:
    - cache
    
    
# command to run tests
script: 
  - sudo -H -E bash -xe ci_test.sh


